notify.c was built using dietlibc to be as small as possible (using "bin-i386/diet gcc -static -o notify notify.c").
If you want to compile it without dietlibc, you can just do

  gcc -o notify notify.c
