To compile notify.c, run

clang -framework CoreFoundation -framework CoreServices -o notify notify.c

or (if you don't have clang)

gcc -framework CoreFoundation -framework CoreServices -o notify notify.c